# Generated by Django 5.2.10 on 2026-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.TextField()),
                ('enr_num', models.IntegerField()),
                ('father_name', models.TextField()),
                ('mother_name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uni_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.TextField()),
                ('enr_num', models.IntegerField()),
                ('course', models.TextField()),
                ('sem', models.IntegerField()),
                ('section', models.TextField()),
            ],
        ),
    ]
